# Generated by Django 4.2.1 on 2023-09-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(default='0', max_length=50)),
                ('password', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tenantname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlatNumber', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=255)),
                ('Adhar', models.CharField(max_length=50)),
                ('rent', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
