# Generated by Django 4.2.1 on 2023-09-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainmeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterNo', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=50)),
                ('unitConsumed', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Submeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenantName', models.CharField(max_length=100)),
                ('meterID', models.CharField(max_length=20)),
                ('previousReading', models.CharField(max_length=50)),
                ('currentReading', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tankerentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=50)),
                ('totalTanker', models.CharField(max_length=100)),
                ('amtPerTanker', models.CharField(max_length=50)),
                ('numOfTenants', models.CharField(max_length=20)),
            ],
        ),
    ]
