# Generated by Django 4.2.1 on 2023-10-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tenantname_todaysdate_alter_tenantname_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmeter',
            name='todaysdate',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='mainmeter',
            name='amount',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='mainmeter',
            name='meterNo',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='mainmeter',
            name='month',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='mainmeter',
            name='unitConsumed',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='mainmeter',
            name='year',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
