# Generated by Django 4.2.1 on 2023-10-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mainmeter_todaysdate_alter_mainmeter_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submeter',
            name='todaysdate',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='submeter',
            name='currentReading',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='submeter',
            name='meterID',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='submeter',
            name='month',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='submeter',
            name='previousReading',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='submeter',
            name='tenantName',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='submeter',
            name='year',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
