# Generated by Django 4.2.1 on 2023-10-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_submeter_todaysdate_alter_submeter_currentreading_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submeter',
            old_name='month',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='submeter',
            name='year',
        ),
    ]
